float32 x           # meters to move on x
float32 y           # meters to move on y
---
bool finished       # True if the robot reached the goal, False otherwise
---
bool finished       # True if the robot reached the goal, False otherwise